services:
  app:
    # ビルド設定(Dcokerfileを使用)
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BLOG_CLD_FLONT_BASE_URL: https://d2z072fjnbmllc.cloudfront.net/
        NEXT_PUBLIC_BLOG_CLD_FLONT_IMAGE_URL: https://d2z072fjnbmllc.cloudfront.net
        NEXT_PUBLIC_BASIC_AUTH_USER: rootUser
        NEXT_PUBLIC_BASIC_AUTH_PASSWORD: jI4^jRyDg*bD
    # 環境変数設定
    environment:
      # 本番サーバー (next start) を実行
      NODE_ENV: production
      # コンテナ内部のポート (Dockerfileで設定済み)
      PORT: 3000
      # 他の環境変数があればここに追記
      NEXT_PUBLIC_BLOG_CLD_FLONT_BASE_URL: https://d2z072fjnbmllc.cloudfront.net/
      NEXT_PUBLIC_BLOG_CLD_FLONT_IMAGE_URL: https://d2z072fjnbmllc.cloudfront.net
      NEXT_PUBLIC_BASIC_AUTH_USER: rootUser
      NEXT_PUBLIC_BASIC_AUTH_PASSWORD: jI4^jRyDg*bD

    # サービス起動時に実行するコマンド (本番サーバー起動)
    command: npm start --prefix src

    # ポートマッピング
    # 3000番ポートにマッピング
    ports:
      - "3000:3000"

    # 常に再起動する設定 (コンテナが落ちても自動復旧)
    restart: always
