services:
  app:
    # ビルド設定(Dcokerfileを使用)
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BLOG_CLD_FLONT_BASE_URL: ${NEXT_PUBLIC_BLOG_CLD_FLONT_BASE_URL}
        NEXT_PUBLIC_BLOG_CLD_FLONT_IMAGE_URL: ${NEXT_PUBLIC_BLOG_CLD_FLONT_IMAGE_URL}
    env_file:
    - .env
    # Cloud Watchにログ飛ばす設定
    logging:
          driver: "awslogs"
          options:
            awslogs-region: "ap-northeast-1"  # 東京リージョンの場合
            awslogs-group: "NextJS-Docker-Logs" # CloudWatch上のグループ名
            awslogs-stream: "app-container"     # ログストリーム名
            awslogs-create-group: "true"        # グループがなければ自動作成

    # サービス起動時に実行するコマンド (本番サーバー起動)
    command: npm start

    # ポートマッピング
    # 3000番ポートにマッピング
    ports:
      - "3000:3000"

    # 常に再起動する設定 (コンテナが落ちても自動復旧)
    restart: always
