import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shota Portpolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 1. ナビゲーションバー (ヘッダー) - stickyで固定 */}
        <header className="sticky top-0 z-10 w-full bg-white/90 backdrop-blur-sm dark:bg-zinc-900/90 shadow-md">
          <nav className="w-full max-w-4xl mx-auto flex justify-between items-center py-4 px-6">
            <span className="text-xl font-bold text-indigo-600 dark:text-indigo-400">
              千葉翔太 | Portfolio
            </span>
            <div className="space-x-6 text-sm font-medium">
              <a href="/" className="hover:text-indigo-600 transition-colors">TOPページ</a>
              {/* 変更: 別ページへのリンクに変更 */}
              <Link href="/projects" className="hover:text-indigo-600 transition-colors">Webアプリ・作品</Link>
              {/* 変更: 別ページへのリンクに変更 */}
              <Link href="/blog" className="hover:text-indigo-600 transition-colors">技術ブログ</Link>
              <Link href="/contact" className="hover:text-indigo-600 transition-colors">Contact</Link>
            </div>
          </nav>
        </header>

        {/* メインコンテンツ */}
        {children}

        {/* フッター */}
        <footer className="py-6 border-t border-zinc-200 dark:border-zinc-700 text-center text-sm text-zinc-500 dark:text-zinc-400 mt-10">
          &copy; {new Date().getFullYear()} 千葉翔太 Portfolio. Built with Next.js & Tailwind CSS.
        </footer>
      </body>
    </html>
  );
}
